# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giancedrickepilan/dev/native/opengl-demo/lib/glm/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/giancedrickepilan/dev/native/opengl-demo/lib/glm/glm/CMakeLists.txt))

/Users/giancedrickepilan/dev/native/opengl-demo/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/giancedrickepilan/dev/native/opengl-demo -B/Users/giancedrickepilan/dev/native/opengl-demo/xcode
